name: car_go_together
description: A community based carpooling application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  
  # Firebase packages
  # firebase_core: ^2.14.0
  # firebase_auth: ^4.7.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  firebase_auth: ^5.5.2
  
  firebase_core: ^3.13.0
  
  # State management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  
  # Location and maps
  google_maps_flutter: 2.12.1
  geolocator: 14.0.0
  
  geocoding: 3.0.0
  location: 8.0.0
  
  # UI components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.1
  image_picker: ^1.1.2
  
  # Network and API
  http: ^1.1.0
  dio: ^5.2.1+1
  connectivity_plus: ^5.0.1
  
  # Local storage
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^12.1.3
  
  # Others
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.1.12
  permission_handler: ^12.0.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.15
  timeago: ^3.4.0
  logger: ^1.4.0
  logging: ^1.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.2
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# Flutter launcher icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23
  
# Flutter native splash screen configuration
flutter_native_splash:
  color: "#4CAF50"
  image: assets/images/splash_logo.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:  
    - images/reduce_cost.png
    - images/save_environment.png
    - images/stress_free.png